default: &default
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  adapter: sqlite3
  database: db/development.sqlite3

test:
  <<: *default
  adapter: sqlite3
  database: db/test.sqlite3

production:
  primary:
    <<: *default
    adapter: postgresql
    url: <%= ENV["DATABASE_URL"] %>

  cable:
    <<: *default
    adapter: postgresql
    url: <%= ENV.fetch("CABLE_DATABASE_URL", ENV["DATABASE_URL"]) %>

  queue:
    <<: *default
    adapter: postgresql
    url: <%= ENV.fetch("QUEUE_DATABASE_URL", ENV["DATABASE_URL"]) %>

  cache:
    <<: *default
    adapter: postgresql
    url: <%= ENV.fetch("CACHE_DATABASE_URL", ENV["DATABASE_URL"]) %>

